 /* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.praktikum9;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;

/**
 *
 * @author ASUS
 */
public class TambahDataPanel extends javax.swing.JPanel {
    private ButtonGroup genderButtonGroup;
    private boolean isUpdateMode = false;
    private Mahasiswa mahasiswaUpdate = null;

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        initComponents();
}
    
   public TambahDataPanel(Mahasiswa mahasiswa) {
        initComponents();
        genderButtonGroup = new ButtonGroup();
        genderButtonGroup.add(lakiLakiRadioButton);
        genderButtonGroup.add(perempuanRadioButton);

        this.isUpdateMode = true;
        this.mahasiswaUpdate = mahasiswa;

        namaTextField.setText(mahasiswa.getNama());
        nimTextField.setText(mahasiswa.getNim());
        prodiComboBox.setSelectedItem(mahasiswa.getProdi());

        if (mahasiswa.getJenisKelamin().equalsIgnoreCase("Laki-Laki")) {
            lakiLakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }

        aktifCheckBox.setSelected(mahasiswa.isActive());
        jButtonKirim.setText("Update");
        jLabel1.setText("Update Data Mahasiswa");
    } 
    
    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
        genderButtonGroup.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        namaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prodiJLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        aktifCheckBox = new javax.swing.JCheckBox();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jButtonKirim = new javax.swing.JButton();
        prodiComboBox = new javax.swing.JComboBox<>();
        namaAlert = new javax.swing.JLabel();
        prodiAlert = new javax.swing.JLabel();
        jkAlert = new javax.swing.JLabel();
        statusAlert = new javax.swing.JLabel();
        nimAlert = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(530, 400));
        setLayout(new java.awt.CardLayout());

        namaTextField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("NIM");

        prodiJLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        prodiJLabel.setText("Prodi");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setText("Status");

        nimTextField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        aktifCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aktifCheckBox.setText("Aktif");

        jenisKelamin.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lakiLakiRadioButton.setText("Pria");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        jenisKelamin.add(perempuanRadioButton);
        perempuanRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perempuanRadioButton.setText("Wanita");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        jButtonKirim.setBackground(new java.awt.Color(204, 255, 204));
        jButtonKirim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonKirim.setText("KIRIM");
        jButtonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKirimActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Kimia", "S1 Teknik Lingkungan", "S1 Teknik Sipil", "" }));
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        statusAlert.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prodiJLabel)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(namaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                    .addComponent(aktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel1))
                                    .addComponent(namaAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nimAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nimTextField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(prodiAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jkAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lakiLakiRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(perempuanRadioButton))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButtonKirim)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(nimAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodiJLabel)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodiAlert)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jkAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aktifCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAlert)
                .addGap(25, 25, 25)
                .addComponent(jButtonKirim)
                .addGap(141, 141, 141))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void jButtonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKirimActionPerformed
        // TODO add your handling code here:                       
    String nama = namaTextField.getText();
    String nim = nimTextField.getText();
    String prodi = (String) prodiComboBox.getSelectedItem();
    String jenisKelamin = "";
    if (lakiLakiRadioButton.isSelected()) {
        jenisKelamin = "Laki-Laki";
    } else if (perempuanRadioButton.isSelected()) {
        jenisKelamin = "Perempuan";
    }
    boolean isActive = aktifCheckBox.isSelected(); 
    
    if (nama.equals("") || nim.equals("")) {
        JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                + "- Nama atau NIM tidak terisi");
        
    } 
    
    if (isUpdateMode && mahasiswaUpdate != null){
            mahasiswaUpdate.setNama(nama);
            mahasiswaUpdate.setNim(nim);
            mahasiswaUpdate.setProdi(prodi);
            mahasiswaUpdate.setJenisKelamin(jenisKelamin);
            mahasiswaUpdate.setActive(isActive);
            
            for (Mahasiswa m : Mahasiswa.mahasiswas) {
                if (!m.equals(mahasiswaUpdate) && m.getNim().equals(nim)) {
                    JOptionPane.showMessageDialog(this, 
                        "Gagal menambahkan data\nData mahasiswa dengan NIM " 
                                + nim + " sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
                  
     JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui!", "Success", 
            JOptionPane.PLAIN_MESSAGE);
     clearForm();        
    }
    else if (jenisKelamin.equals("")) {
        JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                + "- Opsi jenis kelamin belum dipilih");
    } else if (prodi.equals("")) {
        JOptionPane.showMessageDialog(this, "Gagal menambahkan data:\n"
                + "- Opsi prodi belum dipilih");
    } else if (!nama.matches("^[a-zA-Z ]+$")) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                + "- Terdapat nomor atau karakter spesial pada Nama");
    } else if (nim.matches(".*[a-zA-Z].*") || nim.matches(".*[^a-zA-Z0-9].*")) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                + "- Terdapat alfabet atau karakter spesial pada NIM");
    } else if (nim.length() != 10) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                + "- Jumlah digit pada NIM kurang dari 10");
    } else {
        boolean sudahAda = false;
        String namaDuplikat = "";

        for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
            if (mhs.getNim().equals(nim)) {
                sudahAda = true;
                namaDuplikat = mhs.getNama();
                break;
            }
        }
        if (sudahAda) {
            JOptionPane.showMessageDialog(this,"Data gagal ditambahkan:\n" +
                "- NIM sudah terdaftar atas nama: " + namaDuplikat);
        } else {
            Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
            Mahasiswa.mahasiswas.add(mahasiswa);
            JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
            clearForm();   
        }
      }  
    }//GEN-LAST:event_jButtonKirimActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JButton jButtonKirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JLabel jkAlert;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JLabel namaAlert;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nimAlert;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JLabel prodiAlert;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JLabel prodiJLabel;
    private javax.swing.JLabel statusAlert;
    // End of variables declaration//GEN-END:variables
}
